// Outline generator: clips each map's region out of the public-domain Natural
// Earth world polygons, projects it to fit that map's existing city layout, and
// emits Swift outline arrays (faint land backgrounds). Run:
//   node src/gen-outlines.ts <path-to-ne_110m_admin_0_countries.geojson>
//
// Natural Earth is public domain (naturalearthdata.com/about/terms-of-use).
import { readFileSync, writeFileSync } from "node:fs";
import { MAPS } from "./map.ts";

type Pt = [number, number];
type BBox = [number, number, number, number]; // [minLon, minLat, maxLon, maxLat]

// Geographic bbox per map (which slice of the world to draw behind it). Only
// maps with a meaningful landmass outline are listed; state/city/lake maps are
// handled separately later.
const REGIONS: Record<string, BBox> = {
  europe: [-11, 35, 40, 62],
  germany: [5, 47, 16, 55.5],
  france: [-5, 41, 9, 51.5],
  uk: [-11, 49.5, 2, 61],
  switzerland: [5.8, 45.7, 10.6, 47.9],
  nordic: [4, 54, 32, 71],
  india: [67, 6, 90, 36],
  africa: [-19, -36, 52, 38],
  asia: [44, 4, 150, 61],
  netherlands: [3.2, 50.6, 7.4, 53.7],
  italy: [6, 36, 19, 47.6],
  japan: [128, 30, 146, 46],
  poland: [13.8, 48.8, 24.5, 55.2],
  oldwest: [-125, 28, -94, 49.5],
  world: [-170, -56, 190, 72],
};

const geo = JSON.parse(readFileSync(process.argv[2], "utf8"));

// Sutherland-Hodgman clip of a ring against an axis-aligned bbox.
function clip(ring: Pt[], [minX, minY, maxX, maxY]: BBox): Pt[] {
  const edges: ((p: Pt) => boolean)[] = [
    (p) => p[0] >= minX, (p) => p[0] <= maxX, (p) => p[1] >= minY, (p) => p[1] <= maxY,
  ];
  const inter: ((a: Pt, b: Pt) => Pt)[] = [
    (a, b) => [minX, a[1] + (b[1] - a[1]) * ((minX - a[0]) / (b[0] - a[0]))],
    (a, b) => [maxX, a[1] + (b[1] - a[1]) * ((maxX - a[0]) / (b[0] - a[0]))],
    (a, b) => [a[0] + (b[0] - a[0]) * ((minY - a[1]) / (b[1] - a[1])), minY],
    (a, b) => [a[0] + (b[0] - a[0]) * ((maxY - a[1]) / (b[1] - a[1])), maxY],
  ];
  let out = ring;
  for (let e = 0; e < 4; e++) {
    const inp = out; out = [];
    for (let i = 0; i < inp.length; i++) {
      const cur = inp[i], prev = inp[(i + inp.length - 1) % inp.length];
      const curIn = edges[e](cur), prevIn = edges[e](prev);
      if (curIn) {
        if (!prevIn) out.push(inter[e](prev, cur));
        out.push(cur);
      } else if (prevIn) out.push(inter[e](prev, cur));
    }
    if (out.length === 0) return [];
  }
  return out;
}

// Drop points closer than eps to keep ring sizes reasonable.
function simplify(ring: Pt[], eps: number): Pt[] {
  const out: Pt[] = [];
  for (const p of ring) {
    const last = out[out.length - 1];
    if (!last || Math.hypot(p[0] - last[0], p[1] - last[1]) >= eps) out.push(p);
  }
  return out;
}

function ringsOf(geom: any): Pt[][] {
  if (geom.type === "Polygon") return [geom.coordinates[0]];
  if (geom.type === "MultiPolygon") return geom.coordinates.map((poly: Pt[][]) => poly[0]);
  return [];
}

const lines: string[] = [
  "import Foundation",
  "",
  "// Generated by src/gen-outlines.ts from Natural Earth (public domain).",
  "// Faint land outlines per map, projected to fit each board's city layout.",
  "extension BoardGeometry {",
  "    static let mapOutlines: [String: [[(Double, Double)]]] = [",
];

for (const [id, bbox] of Object.entries(REGIONS)) {
  const map = MAPS[id];
  if (!map) { console.warn("no map for", id); continue; }
  const cx = map.cities.map((c) => c.x), cy = map.cities.map((c) => c.y);
  const cx0 = Math.min(...cx), cx1 = Math.max(...cx), cy0 = Math.min(...cy), cy1 = Math.max(...cy);
  const [minLon, minLat, maxLon, maxLat] = bbox;
  const sx = (lon: number) => cx0 + ((lon - minLon) / (maxLon - minLon)) * (cx1 - cx0);
  const sy = (lat: number) => cy0 + ((maxLat - lat) / (maxLat - minLat)) * (cy1 - cy0); // north -> top

  const rings: Pt[][] = [];
  for (const f of geo.features) {
    for (const ring of ringsOf(f.geometry)) {
      const clipped = clip(ring as Pt[], bbox);
      if (clipped.length < 4) continue;
      const proj = simplify(clipped.map(([lon, lat]) => [sx(lon), sy(lat)] as Pt), 0.006);
      if (proj.length < 4) continue;
      // Drop tiny slivers (area in normalized units).
      let area = 0;
      for (let i = 0; i < proj.length; i++) {
        const a = proj[i], b = proj[(i + 1) % proj.length];
        area += a[0] * b[1] - b[0] * a[1];
      }
      if (Math.abs(area) / 2 < 0.0006) continue;
      rings.push(proj);
    }
  }
  rings.sort((a, b) => b.length - a.length);
  const body = rings.map((r) =>
    "        [" + r.map(([x, y]) => `(${x.toFixed(4)}, ${y.toFixed(4)})`).join(", ") + "]"
  ).join(",\n");
  lines.push(`    "${id}": [\n${body}\n    ],`);
  console.log(`${id}: ${rings.length} rings, ${rings.reduce((n, r) => n + r.length, 0)} pts`);
}

lines.push("    ]", "}", "");
writeFileSync("ios/MessagesExtension/UI/MapOutlines.swift", lines.join("\n"));
console.log("wrote ios/MessagesExtension/UI/MapOutlines.swift");
